//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace Assets.Scripts.Engine.Effects.MinionEffects
{
	class ProtectorEffect : MinionEffect
	{
		public ProtectorEffect()
		{
			remainingTime = 3.0f;
		}
		
		public override void step(Minions.Minion minion)
		{
			for (int i = 0; i < minion.stats.resistancesMult.Count; ++i )
			{
				minion.stats.resistancesMult[i] *= 1.3f;
			}
		}
	}
}

