//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Assets.Scripts.Engine.Minions;
using Assets.Scripts.Engine;
using Assets.Scripts.Engine.Helpers;
using UnityEngine;


namespace Assets.Scripts.Engine.Minions.Chemistry
{
	public class ProtectorMinion : ChemistryMinion
	{
		private static int cost = 3500;
		private static int upgradeCost = 0;
		private static int income = 139;
		private static int killGold = 1175;
		private static int healthCost = 1;
		
		public float DEFAULT_EFFECT_RADIUS = 2.0f;
		public float DEFAULT_EFFECT_COOLDOWN_TIME = 3.0f;
		
		public ProtectorMinion(): base()
		{
			// butun initializationlari burada yap. yok efendim can setlemek, yok efendim movementspeed bilmemne.
			stats.healthTotal = stats.health = 1300;
			stats.baseMovementSpeed = 0.9f;
		}

		public override int getIncome()
		{
			return income;
		}
		
		public override int getKillGold()
		{
			return killGold;
		}
		
		public override int getHealthCost()
		{
			return killGold;
		}
		
		public override int getCost()
		{
			return cost;
		}

		public override string getName()
		{
			return "Protector Minion";
		}
		
		#region implemented abstract members of Minion
		
		protected override float getLocalHeadHeight ()
		{
			return 0.3f;
		}
		
		#endregion
	}
}

